#!/bin/sh

set -eu

WORKDIR=$(mktemp -d)
trap "rm -rf $WORKDIR" 0 INT QUIT ABRT PIPE TERM
cd $WORKDIR
cat <<EOF > meson.build
project('debian clang package test', 'c')
e = executable('prog', 'prog.c')
test('debtest', e)
EOF
cat <<EOF > prog.c
int main(int argc, char **argv) {
  return 0;
}
EOF
mkdir build
CC=clang meson build
ninja -C build test
